# Generated by Django 4.2.2 on 2023-06-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finanzas',
        ),
    ]
