# Generated by Django 4.2.2 on 2023-06-14 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion1', '0003_gestorfinanzas_finanzas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestorFinanzas',
            new_name='PerfilGestorFinanzas',
        ),
    ]
