# Generated by Django 4.2.2 on 2023-06-14 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_rename_gestorfinanzas_perfilgestorfinanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
