# Generated by Django 4.2.2 on 2023-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_aporte_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
