# Generated by Django 4.2.2 on 2023-06-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0006_alter_aporte_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='beneficiado',
        ),
        migrations.RemoveField(
            model_name='finanzas',
            name='aportes',
        ),
        migrations.RemoveField(
            model_name='finanzas',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='perfilaportador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilbeneficiado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='perfilgestorfinanzas',
            name='user',
        ),
        migrations.DeleteModel(
            name='Aporte',
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.DeleteModel(
            name='Finanzas',
        ),
        migrations.DeleteModel(
            name='PerfilAportador',
        ),
        migrations.DeleteModel(
            name='PerfilBeneficiado',
        ),
        migrations.DeleteModel(
            name='PerfilGestorFinanzas',
        ),
    ]
