# Generated by Django 4.2.2 on 2023-06-14 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
