# Generated by Django 4.2.2 on 2023-06-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilaportador',
            options={'permissions': [('permiso_aportador', 'Puede acceder a las interfaces de aportador')]},
        ),
        migrations.AlterModelOptions(
            name='perfilbeneficiado',
            options={'permissions': [('permiso_beneficiado', 'Puede acceder a las interfaces de beneficiado')]},
        ),
        migrations.AlterModelOptions(
            name='perfilgestorfinanzas',
            options={'permissions': [('permiso_finanzas', 'Puede acceder a las interfaces de finanzas')]},
        ),
    ]
