# Generated by Django 4.2.2 on 2023-06-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0012_alter_perfilaportador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilaportador',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='perfilbeneficiado',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='perfilgestorfinanzas',
            name='clave',
        ),
    ]
