# Generated by Django 4.2.2 on 2023-06-15 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion1', '0014_remove_beneficio_beneficiado_remove_finanzas_aportes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGestorFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('permiso_finanzas', 'Puede acceder a las interfaces de finanzas')],
            },
        ),
        migrations.CreateModel(
            name='PerfilBeneficiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('permiso_beneficiado', 'Puede acceder a las interfaces de beneficiado')],
            },
        ),
        migrations.CreateModel(
            name='PerfilAportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('permiso_aportador', 'Puede acceder a las interfaces de aportador')],
            },
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beneficios_entregados', models.IntegerField()),
                ('total_aportes_entregados', models.IntegerField()),
                ('aportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.aporte')),
                ('beneficios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.beneficio')),
            ],
        ),
        migrations.AddField(
            model_name='beneficio',
            name='beneficiado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.perfilbeneficiado'),
        ),
        migrations.AddField(
            model_name='aporte',
            name='aportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.perfilaportador'),
        ),
    ]
