# Generated by Django 4.2.2 on 2023-06-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0016_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='aportador',
        ),
    ]
